### ISSUE TITLE
what is NGINX_FILES_PATH value in our case using proxy ?

### ISSUE THREAD

**Issue by dipenpatel235** [SUPLA/supla-docker#12]
NGINX_FILES_PATH=/path/to/your/nginx/data

**Comment by fracz** [comment]
See [the original proxy project](https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion). This is the path where [nginx configuration](https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/blob/master/docker-compose.yml#L13-L17) is stored.
